#!usr/bin/env bash

PLAID_CLIENT_ID=5f3f5c7bd4530d001106214d \
PLAID_SECRET=8a93ca80daf1eef77524335027fe7e \
PLAID_PRODUCTS=transactions \
PLAID_COUNTRY_CODES=US \
PLAID_ENV=sandbox \
python pServer.py